server:
  port: 8084

spring:
  application:
    name: admin-service

services:
  group-service:
    url: http://localhost:8083
  prayer-service:
    url: http://localhost:8082


management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

cookie:
  secure: false
---
spring:
  config:
    activate:
      on-profile: local

aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: eu-west-1

cookie:
  secure: false
