server:
  port: 8081

spring:
  application:
    name: identity-service
  profiles:

services:
  group-service:
    url: http://localhost:8083


management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: local

aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: eu-west-1
