server:
  port: 8083

spring:
  application:
    name: group-service

management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
---
spring:
  config:
    activate:
      on-profile: local

aws:
  dynamodb:
    endpoint: http://localhost:8000
    region: eu-west-1
  eventbridge:
    endpoint: http://localhost:4566
    region: eu-west-1
    bus: prayer-link-bus

