server:
  port: 8082

spring:
  application:
    name: prayer-service

aws:
  eventbridge:
    bus: prayer-link-bus

management:
  health:
    diskspace:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always

