server:
  port: 8085

spring:
  application:
    name: notification-service
  main:
    web-application-type: none
  cloud:
    aws:
      sqs:
        listener:
          auto-startup: false
---
spring:
  config:
    activate:
      on-profile: local
  main:
    web-application-type: none
  cloud:
    aws:
      sqs:
        listener:
          auto-startup: true

aws:
  sqs:
    endpoint: http://localhost:4566
    region: eu-west-1
  ses:
    endpoint: http://localhost:4566
    region: eu-west-1

services:
  group-service:
    url: http://localhost:8083
  prayer-service:
    url: http://localhost:8082


app:
  domain: localhost:5173  # frontend local dev server
  mail:
    from: ${APP_MAIL_FROM:prayers@prayer-link.org}

hmac:
  secret-key: default-secret-key-change-me-in-production
