name: Group Service CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/group-service-ci.yml'
      - '.github/workflows/service-workflow.yml'
      - 'services/common/**'
      - 'services/group-service/**'
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]
    paths:
      - '.github/workflows/group-service-ci.yml'
      - '.github/workflows/service-workflow.yml'
      - 'services/common/**'
      - 'services/group-service/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      packages: write

    secrets: inherit

    with:
      service: group-service
      smoke-test-path: '/api/groups/validate?passcode=a'
      smoke-test-method: 'GET'
      smoke-test-expected-status: '400'