name: Identity Service CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/identity-service-ci.yml'
      - '.github/workflows/service-workflow.yml'
      - 'services/common/**'
      - 'services/identity-service/**'
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]
    paths:
      - '.github/workflows/identity-service-ci.yml'
      - '.github/workflows/service-workflow.yml'
      - 'services/common/**'
      - 'services/identity-service/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  packages: write

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      packages: write

    secrets: inherit

    with:
      service: identity-service
      smoke-test-path: '/api/identity/register'
      smoke-test-method: 'POST'
      smoke-test-expected-status: '400'
      smoke-test-body: '{}'