name: Notification Service CI

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/notification-service-ci.yml'
      - '.github/workflows/service-workflow.yml'
      - 'services/common/**'
      - 'services/notification-service/**'
  pull_request:
    types: [opened, synchronize]
    branches: [ main ]
    paths:
      - '.github/workflows/notification-service-ci.yml'
      - '.github/workflows/service-workflow.yml'
      - 'services/common/**'
      - 'services/notification-service/**'

permissions:
  id-token: write
  contents: read
  code-quality: write
  pull-requests: write
  packages: write

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      packages: write

    secrets: inherit

    with:
      service: notification-service